// Generated by CoffeeScript 1.5.0
(function() {
  var App;

  App = Ember.Application.create();

  App.ApplicationController = Ember.Controller.extend();

  App.ApplicationView = Ember.View.extend({
    templateName: "application"
  });

  App.AllContributorsController = Ember.ArrayController.extend();

  App.AllContributorsView = Ember.View.extend({
    templateName: "contributors"
  });

  App.OneContributorView = Ember.View.extend({
    templateName: "a-contributor"
  });

  App.OneContributorController = Ember.ObjectController.extend();

  App.DetailsView = Ember.View.extend({
    templateName: "contributor-details"
  });

  App.Router = Ember.Router.extend({
    enableLogging: true,
    root: Ember.Route.extend({
      contributors: Ember.Route.extend({
        route: "/",
        showContributor: Ember.Route.transitionTo('aContributor'),
        connectOutlets: function(router) {
          return router.get("applicationController").connectOutlet("allContributors", App.Contributor.find());
        }
      }),
      aContributor: Ember.Route.extend({
        route: "/:githubUserName",
        showAllContributors: Ember.Route.transitionTo("contributors"),
        connectOutlets: function(router, context) {
          return router.get("applicationController").connectOutlet("oneContributor", context);
        },
        serialize: function(router, context) {
          return {
            githubUserName: context.get('login')
          };
        },
        deserialize: function(router, urlParams) {
          return App.Contributor.find(urlParams.githubUserName);
        },
        initialState: "details",
        details: Ember.Route.extend({
          route: "/",
          connectOutlets: function(router) {
            router.get('oneContributorController.content').loadMoreDetails();
            return router.get("oneContributorController").connectOutlet("details");
          }
        }),
        repos: Ember.Route.extend({
          route: "/repos",
          connectOutlets: function(router) {
            return router.get("oneContributorController").connectOutlet("repos");
          }
        })
      })
    })
  });

  App.initialize();

  App.Contributor = Ember.Object.extend();

  App.Contributor.reopenClass({
    allContributors: [],
    find: function() {
      $.ajax({
        url: "https://api.github.com/repos/emberjs/ember.js/contributors",
        dataType: "jsonp",
        context: this,
        success: function(response) {
          return response.data.forEach((function(contributor) {
            return this.allContributors.addObject(App.Contributor.create(contributor));
          }), this);
        }
      });
      return this.allContributors;
    },
    findOne: function(username) {
      var contributor;
      contributor = App.Contributor.create({
        login: username
      });
      $.ajax({
        url: "https://api.github.com/repos/emberjs/ember.js/contributors",
        dataType: "jsonp",
        context: contributor,
        success: function(response) {
          return this.setProperties(response.data.findProperty("login", username));
        }
      });
      return contributor;
    },
    loadMoreDetails: function() {
      return $.ajax({
        url: "https://api.github.com/users/" + (this.get('login')),
        context: this,
        dataType: 'jsonp',
        success: function(response) {
          return this.setProperties(response.data);
        }
      });
    }
  });

}).call(this);
